STOP REPLICA;
RESET REPLICA ALL;

DO SLEEP(5);

-- mysql2가 mysql1을 바라보게 설정
CHANGE REPLICATION SOURCE TO 
    SOURCE_HOST='mysql1',
    SOURCE_USER='repl_user',
    SOURCE_PASSWORD='repl1234!',
    SOURCE_PORT=3306,
    SOURCE_SSL=0,
    GET_SOURCE_PUBLIC_KEY=1;

START REPLICA;